---

- name: Run Elasticsearch in a Docker container
  community.docker.docker_container:
    name: arkime_elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:{{ arkime_elasticsearch_version }}
    container_default_behavior: no_defaults
    env:
      discovery.type: single-node
    published_ports:
      - 127.0.0.1:9200:9200
      - 127.0.0.1:9300:9300

- name: Wait for Elasticsearch to accept connections
  wait_for:
    port: 9200
